# Generated by Django 5.2.12 on 2026-04-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_ubicacion_latitud_alter_ubicacion_longitud'),
        ('market', '0002_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='geo.ubicacion'),
        ),
    ]
