# Generated by Django 5.2.12 on 2026-04-10

from decimal import Decimal

from django.db import migrations


def backfill_medellin_location_for_catalog(apps, schema_editor):
    Publicacion = apps.get_model("market", "Publicacion")
    Ubicacion = apps.get_model("geo", "Ubicacion")

    # Ubicación base del catálogo para que el seguimiento siempre tenga un punto real de recogida.
    direccion = "Parque Lleras, Medellín, Antioquia"
    latitud = Decimal("6.208763")
    longitud = Decimal("-75.565053")

    ubicacion, _ = Ubicacion.objects.get_or_create(
        direccion_texto=direccion,
        latitud=latitud,
        longitud=longitud,
    )

    Publicacion.objects.filter(ubicacion__isnull=True).update(ubicacion=ubicacion)


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_alter_ubicacion_latitud_alter_ubicacion_longitud"),
        ("market", "0003_publicacion_ubicacion"),
    ]

    operations = [
        migrations.RunPython(backfill_medellin_location_for_catalog, migrations.RunPython.noop),
    ]
