# Generated by Django 5.2.12 on 2026-03-05 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='ABIERTA', max_length=20)),
                ('distancia_validacion_metros', models.FloatField(default=0.0)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion', to='market.pedido')),
            ],
        ),
    ]
